<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BuildingManagementMvc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.9.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
	<PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
	<PackageReference Include="ClosedXML" Version="0.104.1" />
	<PackageReference Include="FirebaseAdmin" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="firebase-service-account.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>