<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BuildingManagementMvc</RootNamespace>
    <UserSecretsId>01de7570-ddd8-472d-b817-9e0f695e5024</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\workflows\BuildingManagementMVC20260930173859.yml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Firestore" Version="3.9.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="QuestPDF" Version="2024.12.3" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.26.2" />
    <PackageReference Include="ClosedXML" Version="0.104.1" />
    <PackageReference Include="FirebaseAdmin" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Shared.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Shared.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="firebase-service-account.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

<!-- ✅ Localization Resources -->
<ItemGroup>
  <EmbeddedResource Update="Resources\Shared.resx">
    <Generator>ResXFileCodeGenerator</Generator>
    <LastGenOutput>Shared.Designer.cs</LastGenOutput>
  </EmbeddedResource>
  <EmbeddedResource Update="Resources\Shared.ar.resx">
    <Generator></Generator>
    <WithCulture>true</WithCulture>
  </EmbeddedResource>
  <EmbeddedResource Update="Resources\Shared.en.resx">
    <Generator></Generator>
    <WithCulture>true</WithCulture>
  </EmbeddedResource>
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x64\leptonica-1.82.0.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x64\tesseract50.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x86\leptonica-1.82.0.dll" />
</ItemGroup>
<ItemGroup>
  <None Remove="C:\Users\alaa5\.nuget\packages\tesseract\5.2.0\build\\..\x86\tesseract50.dll" />
</ItemGroup>

</Project>