// <auto-generated />
using System;
using BuildingManagementMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildingManagementMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007195502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ApartmentEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("date");

                    b.Property<string>("DisabledReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotifyEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyInApp")
                        .HasColumnType("bit");

                    b.Property<bool>("NotifyWhatsApp")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("OpenDate")
                        .HasColumnType("date");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredPaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SettingsUpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("SettingsUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "FloorId");

                    b.HasIndex("BuildingId", "Number")
                        .IsUnique();

                    b.ToTable("Apartments", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ApartmentWalletMovementsView", b =>
                {
                    b.Property<decimal>("Adjustments")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConfirmedDeposits")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetMovements")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_ApartmentWalletMovements", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AptNumber")
                        .HasColumnType("int");

                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("AuditId");

                    b.HasIndex("BuildingId", "Ts");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BackupHistoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollectionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalDocuments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BackupHistory", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingAdminEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminUid")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BuildingId", "AdminUid");

                    b.HasIndex("AdminUid");

                    b.ToTable("BuildingAdmins", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminPin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminWhatsapp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingNumber")
                        .IsUnique();

                    b.ToTable("Buildings", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingSettingsEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpenseDistribution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceDayOfMonth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VotingQuorumPercent")
                        .HasColumnType("int");

                    b.Property<string>("WhatsappNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId");

                    b.ToTable("BuildingSettings", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.CameraEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Channel")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DvrId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HlsUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RtspPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("DvrId", "Channel")
                        .IsUnique();

                    b.ToTable("Cameras", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DepositEditEntity", b =>
                {
                    b.Property<long>("EditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EditId"));

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ByUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepositId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("NewAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NewNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OldAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OldNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("EditId");

                    b.HasIndex("BuildingId", "DepositId");

                    b.ToTable("DepositEditHistory", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DepositEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelledReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("ConfirmedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReceiptFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceiptFileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReceiptSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "ApartmentId");

                    b.ToTable("Deposits", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DvrEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Dvrs", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ExpenseEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "CategoryKind", "CategoryId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.FinancialCategoryEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("BuildingId", "Kind", "Id");

                    b.ToTable("FinancialCategories", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.FloorEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("BuildingId", "Id");

                    b.ToTable("Floors", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.GlobalSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryApiKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryCloudName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableMaintenance")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableOcr")
                        .HasColumnType("bit");

                    b.Property<bool>("EnablePolls")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableQrAccess")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableWhatsApp")
                        .HasColumnType("bit");

                    b.Property<string>("FirebaseProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPinAttempts")
                        .HasColumnType("int");

                    b.Property<int>("SessionTimeoutDays")
                        .HasColumnType("int");

                    b.Property<string>("StorageMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsappApiToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsappPhoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.MaintenanceRecordEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AddedToExpense")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AddedToExpenseAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("MaintenanceDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.MonthlyApartmentShareEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MonthKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CarryOver")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExpenseShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RevenueShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BuildingId", "MonthKey", "ApartmentId");

                    b.HasIndex("BuildingId", "ApartmentId");

                    b.ToTable("MonthlyApartmentShares", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("RecipientApartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ts")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "RecipientApartmentId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.ToTable("Polls", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollOptionEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PollId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "PollId", "Id");

                    b.ToTable("PollOptions", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollVoteEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PollId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OptionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("BuildingId", "PollId", "ApartmentId");

                    b.HasIndex("BuildingId", "ApartmentId");

                    b.HasIndex("BuildingId", "PollId", "OptionId");

                    b.ToTable("PollVotes", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PresenceEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApartmentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Uid");

                    b.ToTable("Presence", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.QrTokenEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BuildingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UsedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.HasIndex("BuildingId", "ApartmentId");

                    b.ToTable("QrTokens", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ReceiptEntity", b =>
                {
                    b.Property<long>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReceiptId"));

                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OcrAmountGuess")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OcrText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceiptId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.RevenueEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryKind")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RevenueDate")
                        .HasColumnType("date");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "CategoryKind", "CategoryId");

                    b.ToTable("Revenues", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ScheduledBackupSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollectionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LastRunStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBackupsToKeep")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScheduledBackupSettings", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.SyncPendingChangeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Applied")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Applied", "CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("SyncPendingChanges", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisabledReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Uid");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.UserPermissionEntity", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Permission")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Uid", "Permission");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.WalletAdjustmentEntity", b =>
                {
                    b.Property<string>("BuildingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuildingId", "Id");

                    b.HasIndex("BuildingId", "ApartmentId");

                    b.ToTable("WalletAdjustments", (string)null);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ApartmentEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", "Building")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.FloorEntity", "Floor")
                        .WithMany("Apartments")
                        .HasForeignKey("BuildingId", "FloorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.AuditLogEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingAdminEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.UserEntity", "User")
                        .WithMany("BuildingAdmins")
                        .HasForeignKey("AdminUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", "Building")
                        .WithMany("Admins")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingSettingsEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", "Building")
                        .WithOne("Settings")
                        .HasForeignKey("BuildingManagementMvc.Data.Entities.BuildingSettingsEntity", "BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.CameraEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.DvrEntity", "Dvr")
                        .WithMany("Cameras")
                        .HasForeignKey("DvrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dvr");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DepositEditEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.DepositEntity", "Deposit")
                        .WithMany("EditHistory")
                        .HasForeignKey("BuildingId", "DepositId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DepositEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "Apartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DvrEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.FinancialCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("BuildingId", "CategoryKind", "CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.FinancialCategoryEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", "Building")
                        .WithMany("Categories")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.FloorEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.MaintenanceRecordEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.MonthlyApartmentShareEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "Apartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.NotificationEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "RecipientApartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "RecipientApartmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RecipientApartment");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollOptionEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.PollEntity", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("BuildingId", "PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollVoteEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "Apartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.PollOptionEntity", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("BuildingId", "PollId", "OptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.QrTokenEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "Apartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.ReceiptEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.RevenueEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.FinancialCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("BuildingId", "CategoryKind", "CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.UserPermissionEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.UserEntity", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.WalletAdjustmentEntity", b =>
                {
                    b.HasOne("BuildingManagementMvc.Data.Entities.BuildingEntity", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildingManagementMvc.Data.Entities.ApartmentEntity", "Apartment")
                        .WithMany()
                        .HasForeignKey("BuildingId", "ApartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.BuildingEntity", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Apartments");

                    b.Navigation("Categories");

                    b.Navigation("Floors");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DepositEntity", b =>
                {
                    b.Navigation("EditHistory");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.DvrEntity", b =>
                {
                    b.Navigation("Cameras");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.FloorEntity", b =>
                {
                    b.Navigation("Apartments");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollEntity", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.PollOptionEntity", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("BuildingManagementMvc.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("BuildingAdmins");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
