//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildingManagementMvc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BuildingManagementMvc.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام إدارة العمارات.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة العمارات.
        /// </summary>
        internal static string App_ShortName {
            get {
                return ResourceManager.GetString("App_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجوع.
        /// </summary>
        internal static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إغلاق.
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد.
        /// </summary>
        internal static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النسخ.
        /// </summary>
        internal static string Common_Copied {
            get {
                return ResourceManager.GetString("Common_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخ.
        /// </summary>
        internal static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جاري التحميل....
        /// </summary>
        internal static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام إدارة العمارات — نسخة C# MVC.
        /// </summary>
        internal static string Footer_Copyright {
            get {
                return ResourceManager.GetString("Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار العمارة وأدخل رقم الهاتف والـ PIN.
        /// </summary>
        internal static string Login_AdminSubtitle {
            get {
                return ResourceManager.GetString("Login_AdminSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول الأدمن.
        /// </summary>
        internal static string Login_AdminTitle {
            get {
                return ResourceManager.GetString("Login_AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الشقة.
        /// </summary>
        internal static string Login_AptNumber {
            get {
                return ResourceManager.GetString("Login_AptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النظام بيتعرّف على دورك تلقائيًا.
        /// </summary>
        internal static string Login_AutoRoleDetection {
            get {
                return ResourceManager.GetString("Login_AutoRoleDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمارة.
        /// </summary>
        internal static string Login_Building {
            get {
                return ResourceManager.GetString("Login_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — اختار —.
        /// </summary>
        internal static string Login_Choose {
            get {
                return ResourceManager.GetString("Login_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في الاتصال.
        /// </summary>
        internal static string Login_ConnectionError {
            get {
                return ResourceManager.GetString("Login_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباسورد / PIN.
        /// </summary>
        internal static string Login_Credential {
            get {
                return ResourceManager.GetString("Login_Credential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الدور.
        /// </summary>
        internal static string Login_FloorNumber {
            get {
                return ResourceManager.GetString("Login_FloorNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول بـ Google (Super Admin).
        /// </summary>
        internal static string Login_GoogleButton {
            get {
                return ResourceManager.GetString("Login_GoogleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء العملية.
        /// </summary>
        internal static string Login_GoogleCancelled {
            get {
                return ResourceManager.GetString("Login_GoogleCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل الدخول بـ Google.
        /// </summary>
        internal static string Login_GoogleError {
            get {
                return ResourceManager.GetString("Login_GoogleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتصفح منع النافذة.
        /// </summary>
        internal static string Login_GooglePopupBlocked {
            get {
                return ResourceManager.GetString("Login_GooglePopupBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إغلاق نافذة Google.
        /// </summary>
        internal static string Login_GooglePopupClosed {
            get {
                return ResourceManager.GetString("Login_GooglePopupClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدومين غير مصرح به في Firebase.
        /// </summary>
        internal static string Login_GoogleUnauthorizedDomain {
            get {
                return ResourceManager.GetString("Login_GoogleUnauthorizedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيميل / رقم التليفون.
        /// </summary>
        internal static string Login_Identifier {
            get {
                return ResourceManager.GetString("Login_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you@example.com أو +201001234567.
        /// </summary>
        internal static string Login_IdentifierPlaceholder {
            get {
                return ResourceManager.GetString("Login_IdentifierPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أو.
        /// </summary>
        internal static string Login_Or {
            get {
                return ResourceManager.GetString("Login_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📱 تم التعرف على شقتك تلقائياً.
        /// </summary>
        internal static string Login_QrDetectedApt {
            get {
                return ResourceManager.GetString("Login_QrDetectedApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📱 تم التعرف على العمارة تلقائياً.
        /// </summary>
        internal static string Login_QrDetectedBuilding {
            get {
                return ResourceManager.GetString("Login_QrDetectedBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عندك QR سريع؟ اضغط هنا.
        /// </summary>
        internal static string Login_QrHint {
            get {
                return ResourceManager.GetString("Login_QrHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 بس أدخل رقم الواتساب والـ PIN.
        /// </summary>
        internal static string Login_QrHintAdmin {
            get {
                return ResourceManager.GetString("Login_QrHintAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذّر الدخول.
        /// </summary>
        internal static string Login_QuickErrorTitle {
            get {
                return ResourceManager.GetString("Login_QuickErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار العمارة والدور والشقة، وأدخل رقم الواتساب والـ PIN.
        /// </summary>
        internal static string Login_ResidentSubtitle {
            get {
                return ResourceManager.GetString("Login_ResidentSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول الساكن.
        /// </summary>
        internal static string Login_ResidentTitle {
            get {
                return ResourceManager.GetString("Login_ResidentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول.
        /// </summary>
        internal static string Login_Submit {
            get {
                return ResourceManager.GetString("Login_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجل دخولك للمتابعة.
        /// </summary>
        internal static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالبريد الإلكتروني وكلمة المرور.
        /// </summary>
        internal static string Login_SuperAdminSubtitle {
            get {
                return ResourceManager.GetString("Login_SuperAdminSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخول Super Admin.
        /// </summary>
        internal static string Login_SuperAdminTitle {
            get {
                return ResourceManager.GetString("Login_SuperAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الواتساب.
        /// </summary>
        internal static string Login_Whatsapp {
            get {
                return ResourceManager.GetString("Login_Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدمنة.
        /// </summary>
        internal static string Nav_Admins {
            get {
                return ResourceManager.GetString("Nav_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشقق.
        /// </summary>
        internal static string Nav_Apts {
            get {
                return ResourceManager.GetString("Nav_Apts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل.
        /// </summary>
        internal static string Nav_AuditLog {
            get {
                return ResourceManager.GetString("Nav_AuditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسخ الاحتياطي.
        /// </summary>
        internal static string Nav_Backup {
            get {
                return ResourceManager.GetString("Nav_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمارات.
        /// </summary>
        internal static string Nav_Buildings {
            get {
                return ResourceManager.GetString("Nav_Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئات.
        /// </summary>
        internal static string Nav_Categories {
            get {
                return ResourceManager.GetString("Nav_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصروفات.
        /// </summary>
        internal static string Nav_Expenses {
            get {
                return ResourceManager.GetString("Nav_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكتيب.
        /// </summary>
        internal static string Nav_Help {
            get {
                return ResourceManager.GetString("Nav_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        internal static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصيانة.
        /// </summary>
        internal static string Nav_Maintenance {
            get {
                return ResourceManager.GetString("Nav_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سجلي.
        /// </summary>
        internal static string Nav_MyLog {
            get {
                return ResourceManager.GetString("Nav_MyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعداداتي.
        /// </summary>
        internal static string Nav_MySettings {
            get {
                return ResourceManager.GetString("Nav_MySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محفظتي.
        /// </summary>
        internal static string Nav_MyWallet {
            get {
                return ResourceManager.GetString("Nav_MyWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإشعارات.
        /// </summary>
        internal static string Nav_Notifications {
            get {
                return ResourceManager.GetString("Nav_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        internal static string Nav_Permissions {
            get {
                return ResourceManager.GetString("Nav_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصويتات.
        /// </summary>
        internal static string Nav_Polls {
            get {
                return ResourceManager.GetString("Nav_Polls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيرادات.
        /// </summary>
        internal static string Nav_Revenues {
            get {
                return ResourceManager.GetString("Nav_Revenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعدادات.
        /// </summary>
        internal static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المزامنة.
        /// </summary>
        internal static string Nav_Sync {
            get {
                return ResourceManager.GetString("Nav_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوات.
        /// </summary>
        internal static string Nav_Tools {
            get {
                return ResourceManager.GetString("Nav_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحفظة.
        /// </summary>
        internal static string Nav_Wallet {
            get {
                return ResourceManager.GetString("Nav_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتساب.
        /// </summary>
        internal static string Nav_WhatsApp {
            get {
                return ResourceManager.GetString("Nav_WhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدمن.
        /// </summary>
        internal static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساكن.
        /// </summary>
        internal static string Role_Resident {
            get {
                return ResourceManager.GetString("Role_Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير عام.
        /// </summary>
        internal static string Role_SuperAdmin {
            get {
                return ResourceManager.GetString("Role_SuperAdmin", resourceCulture);
            }
        }
    }
}
